#version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - /mnt/docker-data/mysql_data:/var/lib/mysql
    container_name: mysql_container
    hostname: mysql_container
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wordpress_net
    command: '--default-authentication-plugin=caching_sha2_password'
  wordpress:
    image: wordpress:6.6
    depends_on:
      - db
    volumes:
      - /mnt/docker-data/wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_NAME: my_database
      WORDPRESS_DB_USER: my_user
      WORDPRESS_DB_PASSWORD: my_password
      WORDPRESS_DB_HOST: mysql_container:3306
    deploy:
      replicas: 3
      restart_policy:
        condition: any
#      update_config:
#        parallelism: 2
#        delay: 10s
#        failure_action: rollback
    ports:
      - "80"
    expose:
      - "80"
    networks:
      - wordpress_net
#    healthcheck:
#      test: ["CMD-SHELL", "curl -fs http://localhost || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
  nginx:
    image: nginx:1.26
    restart: always
    depends_on:
      - wordpress
#    healthcheck:
#      test: ["CMD-SHELL", "curl -fs http://localhost || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - wordpress_net

networks:
  wordpress_net:
    driver: overlay
    attachable: true
